/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project.hierarchy;

import java.util.Scanner;

import project.hierarchy.files_nagivation.FileNavigator;

public class App {

    public static void main(String[] args) {
        
        Scanner scanner = new Scanner(System.in);
        String path = scanner.nextLine();
        scanner.close();

        FileNavigator fn = new FileNavigator();
        fn.navigate(path);
        fn.print();

    }

}
