/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project.hierarchy;

import project.hierarchy.structure.Directory;
import project.hierarchy.structure.File;
import project.hierarchy.structure.ProjectComponent;

public class App {

    public static void main(String[] args) {
        
        Directory component1 = new Directory("Dir 1");
        Directory component2 = new Directory("Dir 2");
        File component3 = new File("File 1");
        File component4 = new File("File 2");
        
        component1.addChild(component3);
        component2.addChild(component4);
        component1.addChild(component2);

        component1.display("-");

    }

}
